environment:

    global:

        PYTHON: "C:\\conda"
        MINICONDA_VERSION: "latest"
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
        PYTHON_ARCH: "64"
        CONDA_DEPENDENCIES: "numpy numba scipy jinja2"

    matrix:

        - PYTHON_VERSION: "2.7"
          NUMPY_VERSION: "stable"

        - PYTHON_VERSION: "3.5"
          NUMPY_VERSION: "stable"

matrix:
    fast_finish: true

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "%CMD_IN_ENV% conda update --all --yes --quiet"
    - "del ci-helpers\test_env.py /Q"

# Not a .NET project, we build Astropy in the install step instead
build: false

test_script:
    - "%CMD_IN_ENV% python setup.py test"

